### PR TITLE
NVSHAS-9600: Fix disable controller debug category

### PR DESCRIPTION
**Pull request by kyledong-suse**
Fix "set controller <leader_controller_id> debug" will set debug category as empty to disable debug log.

### CODE REVIEW

**Review by yasker — CHANGES_REQUESTED** [review]
There is a typo in the commit (and PR) title.

**Comment by kyledong-suse** [comment]
Thanks for catching it. Fixed

**Review by yasker — APPROVED** [review]
LGTM from coding style perspective.

**Review by williamlin-suse — APPROVED** [review]
LGTM

**Pull request merged**
