### PR TITLE
NVSHAS-9669: Overall security score through REST API

### PR DESCRIPTION
**Pull request by williamlin-suse**
It sets the required permission for calling GET(v1/system/score/metrics)

### CODE REVIEW

**Review by yasker — CHANGES_REQUESTED** [review]
Hmm? Why? There is no comment in the commit. 

Also I don't see the references to those libraries.

**Comment by williamlin-suse** [comment]
It's actually a bug fixing on top of https://github.com/neuvector/neuvector/pull/1680 so that the required permission is specified for calling GET(v1/system/score/metrics)

**Comment by yasker** [comment]
I see. I missed the API call part. Can we put a one-line comment in the commit for the context of this fix? Thanks.

**Comment by williamlin-suse** [comment]
I used "git commit --amend" to change the message of (the last) commit 8af7cbc6c6a833b60d6ed87e8d2b268ed62404fe and then force pushed to main branch.
Now "git log" in main branch shows:
```
commit 8af7cbc6c6a833b60d6ed87e8d2b268ed62404fe (HEAD -> main, origin/main, origin/HEAD)
Author: william.lin <william.lin@suse.com>
Date:   Thu Dec 5 20:04:11 2024 -0800

    NVSHAS-9669: Overall security score through REST API

    It sets the required permission for calling GET(v1/system/score/metrics)

commit e289a9a568bc2a6cc98516ffbd3d6ba44db78cee (origin/release/5.4.2)
Author: william.lin <william.lin@suse.com>
Date:   Tue Dec 3 15:50:14 2024 -0800

    NVSHAS-9652: Observed difference in syslog format in splunk
......
```

**Pull request closed without merging**
