### PR TITLE
NVSHAS-9537: Change existing builders base image to BCI - neuvector portion

### PR DESCRIPTION
**Pull request by kyledong-suse**
1. Use BUILD_IMAGE_TAG=v3
2. Remove all static libs in dp Makefiles, change them all to use shared libs
3. Remove dp/objects and dp/third-party dependencies as all of them are installed in BCI and can be used as dynamic links

### CODE REVIEW

**Comment by yasker** [comment]
This PR LGTM. Not sure how we're going to address the go lint issue in the CI though.

**Comment by kyledong-suse** [comment]
@holyspectral, would you please help to resolve the go lint check for this PR? Thanks.

**Comment by holyspectral** [comment]
yeah the report from linter doesn't look right.  I will investigate.  In the mean time feel free to ignore those reports.

**Review by holyspectral — APPROVED** [review]
Verified on my side except the v3 builder.

**Review by yasker — APPROVED** [review]

**Comment by gfsuse** [comment]
looks good to me

**Review by gfsuse — APPROVED** [review]
looks good to me

**Pull request merged**
